config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :issues do
    resources :issue_comments, only: [:show, :create, :update, :destroy]
  end


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  root 'home#index'
end

app/models/issue.rb
class Issue < ApplicationRecord

  belongs_to :issue_type
  belongs_to :issue_priority
  belongs_to :issue_state
  belongs_to :project

  belongs_to :assigned_user, class_name: "User", :required => false

  has_many :issue_comments, dependent: :destroy

  validates :name, :issue_type_id, :issue_priority_id, :issue_state_id, :project_id, presence: true

  before_save :create_issue_key

  def is_assigned?
    !!assigned_user
  end

  private
  def create_issue_key
    self.issue_key = self.project.create_key_for_new_issue unless self.issue_key
  end

end

app/models/issue_type.rb
class IssueType < ApplicationRecord

  validates :name, :icon, :color, presence: true

  has_many :issues

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]
  before_action :load_form_options, only: [:new, :show, :create]

  # GET /issues
  # GET /issues.json
  def index
    @issues_grid = IssueGrid.new

    if !params[:search] != nil
      @search_input_value = params[:search]
      @issues_grid.search_for(params[:search])
    end

    @issues_grid.set_page(params[:page] || 1)

    @issues = @issues_grid.get_results
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue_comments = @issue.issue_comments.order(:created_at).all

    @issue_comment = IssueComment.new
    @issue_comment.issue = @issue
    @issue_comment.user = current_user
  end

  # GET /issues/new
  def new
    @issue = Issue.new
    @issue.project = Project.find(params[:project_id]) if params[:project_id]
    @issue.issue_state = IssueState.where(completed: false).first
  end

  # GET /issues/1/edit
  def edit
    redirect_to @issue
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)
    @issue.issue_type = IssueType.find(issue_params[:issue_type_id])
    @issue.issue_priority = IssuePriority.find(issue_params[:issue_priority_id])
    @issue.issue_state = IssueState.find(issue_params[:issue_state_id])
    @issue.assigned_user = issue_params[:assigned_user_id] != nil ? User.find(issue_params[:assigned_user_id]) : nil

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      begin
        @issue = Issue.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:error] = "Issue not found"
        redirect_back(fallback_location: issues_path)
      end
    end

    # Only allow a list of trusted parameters through.
    def issue_params
      params.require(:issue).permit(:name, :type, :priority, :description, :state, :project_id, :issue_type_id, :issue_priority_id, :issue_state_id, :assigned_user_id)
    end

    def load_form_options
      @available_projects = Project.order(:name).pluck(:name, :id)
      @available_issue_types = IssueType.pluck(:name, :id)
      @available_issue_priorities = IssuePriority.order(value: :desc).pluck(:name, :id)
      @available_issue_states = IssueState.order(:completed).pluck(:name, :id)
      @available_users = User.order(:email).pluck(:email, :id)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper

end

app/views/issues/_comment_form.html.erb
<h3 class="h4">New comment</h3>

<%= form_with(model: [issue, issue_comment], local: true) do |form| %>
  <% if issue_comment.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(issue_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul class="mb-0">
        <% issue_comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :comment, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_area :comment, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= form.submit value: 'Submit comment', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/issues/_form.html.erb
<%= form_with(model: issue, local: true) do |form| %>
  <% if issue.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul class="mb-0">
        <% issue.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :project_id, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <% if @issue.id != nil %>
        <input type="text" readonly class="form-control-plaintext" id="issue_project_id" value="<%= @issue.project.name %>">
      <% else %>
        <%= form.select :project_id, @available_projects, {prompt: '-- Select project --'}, class: 'form-control' %>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :issue_type_id, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.select :issue_type_id, @available_issue_types, {prompt: '-- Select issue type --'}, {class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :issue_priority_id, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.select :issue_priority_id, @available_issue_priorities, {prompt: '-- Select priority --'}, {class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :issue_state_id, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.select :issue_state_id, @available_issue_states, {prompt: '-- Select state --'}, {class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :assigned_user_id, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.select :assigned_user_id, @available_users, { include_blank: '-- not assigned --'}, {class: 'form-control'} %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/issues/_table.html.erb
<table class="table table-hover table-striped">
  <thead class="thead-light">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Type</th>
      <th>Priority</th>
      <th>State</th>
      <th>Assigned user</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <th><%= link_to issue.issue_key, issue %></th>
        <td><%= issue.name %></td>
        <td>
          <i class="fas fa-<%= issue.issue_type.icon %>" style="color: <%= issue.issue_type.color %>"></i>
          <%= issue.issue_type.name %>
        </td>
        <td>
          <i class="fas fa-<%= issue.issue_priority.icon %>" style="color: <%= issue.issue_priority.color %>"></i>
          <%= issue.issue_priority.name %>
        </td>
        <td>
          <span class="badge badge-secondary" style="background-color: <%= issue.issue_state.color %>"><%= issue.issue_state.name %></span>
        </td>
        <td class="text-center">
          <% if issue.is_assigned? %>
            <img src="<%= user_gravatar_url(issue.assigned_user) %>" alt="<%= issue.assigned_user.email %>" class="rounded-circle" width="32">
          <% else %>
            <small class="text-muted">not assigned</small>
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <!--        <td><%#= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
    <% if @issues.empty? %>
    <tr>
      <td colspan="6">
        <p class="text-muted text-center">No results found</p>
      </td>
    </tr>
    <% end %>
  </tbody>
  <tbody>
    <tr>
      <td colspan="2" class="align-middle">
        <%= @issues_grid.issues_total %> issues total
      </td>
      <td colspan="5" class="align-middle text-right">
        <nav aria-label="Page navigation example" class="d-inline-block">
          <ul class="pagination mb-0">
            <% if @issues_grid.has_previous? %>
            <li class="page-item"><a class="page-link" href="<%= url_for(issues_path(page: @issues_grid.page - 1)) %>">Previous</a></li>
            <% end %>
            <% for p in 1..@issues_grid.last_page %>
            <li class="page-item <%= @issues_grid.is_page?(p) ? 'active' : '' %>"><a href="<%= url_for(issues_path(page: p)) %>" class="page-link"><%= p %></a></li>
            <% end %>
            <% if @issues_grid.has_next? %>
              <li class="page-item"><a class="page-link" href="<%= url_for(issues_path(page: @issues_grid.page + 1)) %>">Next</a></li>
            <% end %>
          </ul>
        </nav>
      </td>
    </tr>
  </tbody>
</table>

app/views/issues/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Issues</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to 'New Issue', new_issue_path, { class: 'btn btn-outline-success'} %>
  </div>
</div>

<%= render 'issues/table', issues: @issues %>

app/views/issues/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">New Issue</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to 'Back', issues_path, { class: 'btn btn-outline-secondary'} %>
  </div>
</div>

<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Issue: <strong><%= @issue.issue_key %></strong></h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to 'Back', issues_path, { class: 'btn btn-outline-secondary mr-2'} %>
  </div>
</div>

<%= render 'form', issue: @issue %>

<div class="mb-4">
  <h2 class="h3">Comments (<%= @issue_comments.size %>)</h2>

  <% @issue_comments.each do |comment| %>
    <div class="media">
      <img src="<%= user_gravatar_url(comment.user) %>" class="mr-3" alt="<%= comment.user.email %>">
      <div class="media-body">
        <h5 class="mt-0"><%= comment.user.email %></h5>
        <p><%= comment.comment %></p>

        <p class="small text-muted">Sent at: <%= comment.created_at %>, <%= link_to 'Delete', [@issue, comment], method: :delete, data: { confirm: 'Are you sure?'} %></p>
      </div>
    </div>
  <% end %>

  <% if @issue_comments.empty? %>
    <p class="text-muted">No comments :(</p>
  <% end %>
</div>

<%= render 'comment_form', issue: @issue, issue_comment: @issue_comment %>