config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :issues do
    resources :issue_comments, only: [:show, :create, :update, :destroy]
  end


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  root 'home#index'
end

app/views/widgets/_assigned_issues.html.erb
<div class="card mb-4">
  <div class="card-header">
    Assigned issues
  </div>
  <div class="card-body p-0">
    <table class="table table-striped table-hover mb-0">
      <thead class="thead-light">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th colspan="3">&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% widget.issues.each do |issue| %>
          <%= render('widgets/issue_row', issue: issue) %>
        <% end %>
        <% if widget.issues.empty? %>
          <tr>
            <td colspan="5">
              <p class="text-muted">No issues found</p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/widgets/_issue_row.html.erb
<tr>
  <th><%= link_to(issue.issue_key, issue_path(issue)) %></th>
  <td><%= issue.name %></td>
  <td title="<%= issue.issue_type.name %>">
    <i class="fas fa-<%= issue.issue_type.icon %>" style="color: <%= issue.issue_type.color %>"></i>
  </td>
  <td>
    <i class="fas fa-<%= issue.issue_priority.icon %>" style="color: <%= issue.issue_priority.color %>"></i>
    <%= issue.issue_priority.name %>
  </td>
  <td>
    <span class="badge badge-secondary" style="background-color: <%= issue.issue_state.color %>"><%= issue.issue_state.name %></span>
  </td>
</tr>

app/views/widgets/_latest_comments.html.erb
<div class="card mb-4">
  <div class="card-header">
    Latest comments
  </div>
  <% widget.comments.each do |comment| %>
  <div class="card-body border-bottom">
    <h5 class="card-title h6">
      <%= link_to("#{comment.issue.issue_key} - #{comment.issue.name}", issue_path(comment.issue)) %>
    </h5>
    <p class="card-text text-muted mb-1"><%= comment.user.email %>, <%= time_ago_in_words(comment.created_at) %> ago</p>
    <p class="card-text"><%= comment.comment %></p>
  </div>
  <% end %>
</div>

app/views/widgets/_latest_issues.html.erb
<div class="card mb-4">
  <div class="card-header">
    Recently created issues
  </div>
  <div class="card-body p-0">
    <table class="table table-striped table-hover mb-0">
      <thead class="thead-light">
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th colspan="3">&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% widget.issues.each do |issue| %>
          <%= render('widgets/issue_row', issue: issue) %>
        <% end %>
        <% if widget.issues.empty? %>
          <tr>
            <td colspan="5">
              <p class="text-muted">No issues found</p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>