config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :issues do
    resources :issue_comments, only: [:show, :create, :update, :destroy]
  end


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  root 'home#index'
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :issues, dependent: :destroy

  validates :name, :project_key, presence: true

  before_save :normalize_project_key

  def issues_total
    (@issues_count ||= fetch_issue_count)[:total]
  end

  def issues_open
    (@issues_count ||= fetch_issue_count)[:open]
  end

  def issues_closed
    (@issues_count ||= fetch_issue_count)[:closed]
  end

  def create_key_for_new_issue
    new_issue_key = "#{self.project_key}-#{self.next_issue_key}"

    self.update_attribute :next_issue_key, (self.next_issue_key + 1)

    new_issue_key
  end

  private
  def normalize_project_key
    self.project_key = self.project_key.upcase
  end

  def fetch_issue_count
    @issues_count = self.issues.joins(:issue_state).group(:completed).count
    @issues_count.default=0

    {
        open: @issues_count[0],
        closed: @issues_count[1],
        total: @issues_count[0] + @issues_count[1],
    }
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @issues = @project.issues

    @issues_grid = IssueGrid.new
    @issues_grid.in_project(@project)

    @issues_grid.set_page(params[:page] || 1)

    @issues = @issues_grid.get_results
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      begin
        if @project.save
          format.html { redirect_to @project, notice: 'Project was successfully created.' }
          format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::RecordNotUnique => e
        @project.errors[:project_key].push e.message

        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :project_key)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul class="mb-0">
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :project_key, class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <% if @project.id != nil %>
        <input type="text" readonly class="form-control" id="project_project_key" value="<%= @project.project_key %>">
      <% else %>
        <%= form.text_field :project_key, class: 'form-control' %>
      <% end %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit nil, {class: 'btn btn-primary'} %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Editing project: <strong><%= @project.name %></strong></h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to 'Show', @project, { class: 'btn btn-outline-primary mr-2'} %>
    <%= link_to 'Back', projects_path, { class: 'btn btn-outline-secondary mr-2'} %>
    <%= link_to 'Destroy', @project, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-outline-danger' %>
  </div>
</div>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Projects</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to 'New Project', new_project_path, { class: 'btn btn-outline-success'} %>
  </div>
</div>

<table class="table table-hover table-striped">
  <thead class="thead-light">
    <tr>
      <th>Key</th>
      <th>Name</th>
      <th>Issues</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <th><%= link_to project.project_key, project %></th>
        <td><%= project.name %></td>
        <td>
          <strong><%= project.issues_open %> open</strong> / <%= project.issues_total %> total
        </td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">New Project</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to 'Back', projects_path, { class: 'btn btn-outline-secondary'} %>
  </div>
</div>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Project: <strong><%= @project.name %></strong></h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <%= link_to 'New Issue', new_issue_path(project_id: @project), { class: 'btn btn-outline-success mr-2'} %>
    <%= link_to 'Edit', edit_project_path(@project), { class: 'btn btn-outline-primary mr-2'} %>
    <%= link_to 'Back', projects_path, { class: 'btn btn-outline-secondary mr-2'} %>
  </div>
</div>

<%= render 'issues/table', issues: @issues %>