config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :issues do
    resources :issue_comments, only: [:show, :create, :update, :destroy]
  end


  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}

  root 'home#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <%= link_to 'Buk issue tracker', root_path, { class: 'navbar-brand col-md-3 col-lg-2 mr-0 px-3' } %>

  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <% if current_user %>
    <%= form_with(url: issues_path, method: :get, data: { remote: false }, class: 'flex-fill') do %>
      <%= search_field_tag(:search, @search_input_value, class: 'form-control form-control-dark w-100', placeholder: 'Search') %>
    <% end %>

    <span class="navbar-text pl-3 pr-3"><%= current_user.email %></span>

    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <%= link_to('Sign out', destroy_user_session_path, method: :delete, class: 'nav-link') %>
      </li>
    </ul>
  <%end%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buk issue tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render('layouts/navbar') %>

  <div class="container-fluid">
    <div class="row">
      <% if current_user %>
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
          <div class="sidebar-sticky pt-3">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link <%= 'active' if current_page? root_path %>" href="<%= url_for(root_path) %>">
                  <span data-feather="home"></span>
                  Dashboard
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link <%= 'active' if current_page? projects_path %>" href="<%= url_for(projects_path) %>">
                  <span data-feather="file"></span>
                  Projects
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link <%= 'active' if current_page? issues_path %>" href="<%= url_for(issues_path) %>">
                  <span data-feather="file"></span>
                  Issues
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
          <% if notice != nil %><p class="alert alert-info mt-4"><%= notice %></p><% end %>
          <% if alert != nil %><p class="alert alert-warning mt-4"><%= alert %></p><% end %>
          <% if flash[:error] != nil %><p class="alert alert-danger mt-4"><%= flash[:error] %></p><% end %>

          <%= yield %>
        </main>
      <% else %>
        <main class="col">
          <% if notice != nil %><p class="alert alert-info mt-4"><%= notice %></p><% end %>
          <% if alert != nil %><p class="alert alert-warning mt-4"><%= alert %></p><% end %>
          <% if flash[:error] != nil %><p class="alert alert-danger mt-4"><%= flash[:error] %></p><% end %>

          <%= yield %>
        </main>
      <% end %>
    </div>
  </div>

  <script src="https://kit.fontawesome.com/2259a4ee68.js" crossorigin="anonymous"></script>
  </body>
</html>